config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :posts do
    get :autocomplete_post_tagcolumn, on: :collection
  end 
  get 'tags/:tag', to: 'welcome#index', as: :tag

end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_ordered_taggable
    # Attachment code for image
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

    # attachement code for audio 
     #has_attached_file :clip
      
     #Here we have removed the validation for the clip to be an optional attachment
     #validates_attachment_presence :clip
     #validates_attachment_content_type :clip, :content_type => [ 'audio/mpg','application/mp3', 'application/x-mp3', 'audio/mpeg', 'audio/mp3' ],
                                #    :message => 'file must be of filetype .mp3'

     #validates_attachment_size :clip, :less_than => 10.megabytes 


     

	def self.get_tag_list
		tag_objects = ActsAsTaggableOn::Tag.all
		tag_list = []
		tag_objects.each do |tag_object|
			tag_list << tag_object.name
		end 
        return tag_list
	end
  def per_page
    2
      
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :tag_cloud
  
  def tag_cloud
  	@tags = Post.tag_counts_on(:tags)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	autocomplete :post, :tagcolumn

	def new
		
	end

	def create
		@post = Post.new post_params
		# tagcolumn is a redundant column just to have a autocomplete feature working
		@post.tagcolumn = @post.tag_list

		if @post.save!
			redirect_to root_path
		else
		    render 'welcome/index' 
		end 
	end

	def edit
		
	end


	private

	def post_params
		params.require(:post).permit(:message, :tag_list, :avatar)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if params[:tag]
			@posts = Post.tagged_with(params[:tag]).paginate(page: params[:page], :per_page => 2)
		else
			@posts = Post.all.order('created_at DESC').paginate(page: params[:page], :per_page => 2)
		end 

		respond_to do |format|
			format.html
			puts("After the respond_to")
			#format.json{render json: @posts}
			format.js
		end 
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def get_autocomplete_tag_list
		Post.get_tag_list
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; AurBatao.com</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            
                <%= link_to "Aur Batao", root_path, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/_sidebarcategories.html.erb
     <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Post Categories</h4>
                    <div class="row">
                        <div class="col-lg-10">
                            <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
                                <%= link_to tag.name, tag_path(tag.name), :class => css_class %>
                            <% end %>
               
                        <!-- /.col-lg-6 -->
                    </div>

app/views/layouts/_sidesearch.html.erb
<!-- Blog Search Well -->
                <div class="well">
                    <h4>Post Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

app/views/layouts/_well.html.erb
<!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aurbatao</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %>
</head>
<body>
	

<div class="container">
	<div class="row">
		<div class="col-md-8">
			
			<%= render 'posts/form' %>
			
			<%= yield %>
		</div>

		<div class="col-md-4">
			<%= render 'layouts/sidebarcategories' %>
			<%= render 'layouts/sidesearch' %>
			<%= render 'layouts/well' %>			
		</div>
		<!-- /.col-md-4 -->
	</div>
	<!-- /.row -->
<hr>

</div>
<!-- /.container -->


<hr>
</body>
<%= render 'layouts/footer' %>
</html>

app/views/posts/_form.html.erb
<!-- getting the tag as json object -->
<% autocomplete_tag_list = get_autocomplete_tag_list() %>

<%= form_for Post.new , html: { multipart: true } do  |f| %>


<div class="form-group">
        <%= f.label :message, "Post Your Thoughts:", class: "col-md-4 control-label message-label" %>
        
          <%= f.text_area :message, class: "form-control" , rows: "7" %>
          
      </div>

      <div class="form-group">
        <%= f.label :tag_list, "Tags:", class: "col-md-4 control-label message-label" %>
        
          <%= f.text_field :tag_list, class: "form-control", placeholder: "Enter tags separated by Comma"  %>
          
          
      </div>
      

      <div class = "form-group">
      	
        
             Attach Image <%= f.file_field :avatar %>
        
           
        
      </div>

  

      <%= f.submit "Submit Post" , class: "btn btn-info" %>

<% end %>


<!-- Ajax for autocomplete -->
  <script>
  $(function() {
    // var availableTags = [
    //   "ActionScript",
    //   "AppleScript",
    //   "Asp",
    //   "BASIC",
    //   "C",
    //   "C++",
    //   "Clojure",
    //   "COBOL",
    //   "ColdFusion",
    //   "Erlang",
    //   "Fortran",
    //   "Groovy",
    //   "Haskell",
    //   "Java",
    //   "JavaScript",
    //   "Lisp",
    //   "Perl",
    //   "PHP",
    //   "Python",
    //   "Ruby",
    //   "Scala",
    //   "Scheme"
    // ];
    //alert("<%= raw get_autocomplete_tag_list.to_json %>");
    var availableTags = <%= raw get_autocomplete_tag_list.to_json %>;
    
    //=============================
    function split( val ) {
      return val.split( /,\s*/ );
    }
    function extractLast( term ) {
      return split( term ).pop();
    }
 
    $( "#post_tag_list" )
      // don't navigate away from the field on tab when selecting an item
      .bind( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).autocomplete( "instance" ).menu.active ) {
          event.preventDefault();
        }
      })
      .autocomplete({
        minLength: 0,
        source: function( request, response ) {
          // delegate back to autocomplete, but extract the last term
          response( $.ui.autocomplete.filter(
            availableTags, extractLast( request.term ) ) );
        },
        focus: function() {
          // prevent value inserted on focus
          return false;
        },
        select: function( event, ui ) {
          var terms = split( this.value );
          // remove the current input
          terms.pop();
          // add the selected item
          terms.push( ui.item.value );
          // add placeholder to get the comma-and-space at the end
          terms.push( "" );
          this.value = terms.join( ", " );
          return false;
        }
      });
    //=============================
    // $( "#post_tag_list" ).autocomplete({
    	
    //   source: availableTags
    // });
  });
  </script>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/welcome/_post.html.erb
<% if @posts %>
  <% @posts.each do |post| %>
    <p class="lead">
    	Posted By <a href="#">Karan</a>
    	

    </p>
    <span class="glyphicon glyphicon-time"></span> Posted on <%=  post.created_at %>
    
    <hr>
    <% if post.avatar.exists? %>
      <%= image_tag post.avatar.url(:medium) %>
    <% end %>
  <p><%= post.message %></p>
  <p> Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> </p>


  <hr>
  <% end %>
<% end %>

<!-- Pager -->
<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @posts, :container => false %>
  </div>

  <br>
  <hr>

app/views/welcome/index.html.erb
<h1 class="page-header">
    Trending Posts
    
</h1>

<div id = 'page-post'>
  <%= render'welcome/post' %>
</div>








<!-- Added javascript to ajaxify the pagination gem -->
<script>
 $(function(){
  $('.apple_pagination a').attr('data-remote', 'true');
 });
</script>

app/views/welcome/index.js.erb
$('#page-post').html(" <%= escape_javascript(render ('welcome/post')) %> ");
console.log("We have sucexxfuly ot th posts: #{@posts}");
$('.apple_pagination a').attr('data-remote', 'true');